// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatHammer.Server.Data;

#nullable disable

namespace StatHammer.Server.Migrations
{
    [DbContext(typeof(StatHammerDbContext))]
    [Migration("20260514130638_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Abilities", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Keywords", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvulnerableSave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Leadership")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Move")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Save")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Toughness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wounds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Models", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.ModelAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("ModelId", "AbilityId")
                        .IsUnique();

                    b.ToTable("ModelAbilities", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.ModelWargear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WargearId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WargearId");

                    b.HasIndex("ModelId", "WargearId")
                        .IsUnique();

                    b.ToTable("ModelWargears", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.ModelWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeaponId");

                    b.HasIndex("ModelId", "WeaponId")
                        .IsUnique();

                    b.ToTable("ModelWeapons", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.OptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WargearId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitOptionId");

                    b.HasIndex("WargearId");

                    b.HasIndex("WeaponId");

                    b.ToTable("OptionItems", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.SimulationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SimulationCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitBId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitAId");

                    b.HasIndex("UnitBId");

                    b.ToTable("SimulationResults", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.TurnStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgBlockedByFnp")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgHits")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgModelsAlive")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgSuccessfulSaves")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgWounds")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgWoundsAlive")
                        .HasColumnType("REAL");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SimulationResultId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SimulationResultId", "TurnNumber", "Side")
                        .IsUnique();

                    b.ToTable("TurnStats", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("UnitId", "AbilityId")
                        .IsUnique();

                    b.ToTable("UnitAbilities", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitKeyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeywordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId");

                    b.HasIndex("UnitId", "KeywordId")
                        .IsUnique();

                    b.ToTable("UnitKeywords", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("UnitId", "ModelId")
                        .IsUnique();

                    b.ToTable("UnitModels", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxSelections")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("UnitOptions", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Wargear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wargears", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Weapons", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.WeaponProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorPiercing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attacks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeaponId");

                    b.ToTable("WeaponProfiles", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.WeaponProfileAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("WeaponProfileId", "AbilityId")
                        .IsUnique();

                    b.ToTable("WeaponProfileAbilities", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.WeaponStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgDamage")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgHits")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgWounds")
                        .HasColumnType("REAL");

                    b.Property<int>("TurnStatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeaponId");

                    b.HasIndex("TurnStatId", "WeaponId")
                        .IsUnique();

                    b.ToTable("WeaponStats", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.ModelAbility", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Model", "Model")
                        .WithMany("ModelAbilities")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.ModelWargear", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Model", "Model")
                        .WithMany("ModelWargears")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Wargear", "Wargear")
                        .WithMany("ModelWargears")
                        .HasForeignKey("WargearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Wargear");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.ModelWeapon", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Model", "Model")
                        .WithMany("ModelWeapons")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Weapon", "Weapon")
                        .WithMany("ModelWeapons")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.OptionItem", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.UnitOption", "UnitOption")
                        .WithMany("OptionItems")
                        .HasForeignKey("UnitOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Wargear", "Wargear")
                        .WithMany()
                        .HasForeignKey("WargearId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StatHammer.Server.Models.Entities.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UnitOption");

                    b.Navigation("Wargear");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.SimulationResult", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Unit", "UnitA")
                        .WithMany()
                        .HasForeignKey("UnitAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Unit", "UnitB")
                        .WithMany()
                        .HasForeignKey("UnitBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnitA");

                    b.Navigation("UnitB");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.TurnStat", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.SimulationResult", "SimulationResult")
                        .WithMany("TurnStats")
                        .HasForeignKey("SimulationResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationResult");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitAbility", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Unit", "Unit")
                        .WithMany("UnitAbilities")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitKeyword", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Keyword", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Unit", "Unit")
                        .WithMany("UnitKeywords")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitModel", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Unit", "Unit")
                        .WithMany("UnitModels")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitOption", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Unit", "Unit")
                        .WithMany("UnitOptions")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.WeaponProfile", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Weapon", "Weapon")
                        .WithMany("WeaponProfiles")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.WeaponProfileAbility", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.WeaponProfile", "WeaponProfile")
                        .WithMany("WeaponProfileAbilities")
                        .HasForeignKey("WeaponProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("WeaponProfile");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.WeaponStat", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.TurnStat", "TurnStat")
                        .WithMany("WeaponStats")
                        .HasForeignKey("TurnStatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TurnStat");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Model", b =>
                {
                    b.Navigation("ModelAbilities");

                    b.Navigation("ModelWargears");

                    b.Navigation("ModelWeapons");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.SimulationResult", b =>
                {
                    b.Navigation("TurnStats");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.TurnStat", b =>
                {
                    b.Navigation("WeaponStats");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Unit", b =>
                {
                    b.Navigation("UnitAbilities");

                    b.Navigation("UnitKeywords");

                    b.Navigation("UnitModels");

                    b.Navigation("UnitOptions");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitOption", b =>
                {
                    b.Navigation("OptionItems");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Wargear", b =>
                {
                    b.Navigation("ModelWargears");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Weapon", b =>
                {
                    b.Navigation("ModelWeapons");

                    b.Navigation("WeaponProfiles");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.WeaponProfile", b =>
                {
                    b.Navigation("WeaponProfileAbilities");
                });
#pragma warning restore 612, 618
        }
    }
}
