// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatHammer.Server.Data;

#nullable disable

namespace StatHammer.Server.Migrations
{
    [DbContext(typeof(StatHammerDbContext))]
    [Migration("20260504132903_AddUnits")]
    partial class AddUnits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Abilities", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Keywords", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvulnerableSave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Leadership")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Move")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Save")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Toughness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wounds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Models", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.ModelAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("ModelId", "AbilityId")
                        .IsUnique();

                    b.ToTable("ModelAbilities", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.ModelWargear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WargearId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WargearId");

                    b.HasIndex("ModelId", "WargearId")
                        .IsUnique();

                    b.ToTable("ModelWargears", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.ModelWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeaponId");

                    b.HasIndex("ModelId", "WeaponId")
                        .IsUnique();

                    b.ToTable("ModelWeapons", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.OptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WargearId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitOptionId");

                    b.HasIndex("WargearId");

                    b.HasIndex("WeaponId");

                    b.ToTable("OptionItems", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("UnitId", "AbilityId")
                        .IsUnique();

                    b.ToTable("UnitAbilities", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitKeyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeywordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId");

                    b.HasIndex("UnitId", "KeywordId")
                        .IsUnique();

                    b.ToTable("UnitKeywords", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("UnitId", "ModelId")
                        .IsUnique();

                    b.ToTable("UnitModels", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxSelections")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("UnitOptions", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Wargear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wargears", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Weapons", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.WeaponProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorPiercing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attacks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeaponId");

                    b.ToTable("WeaponProfiles", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.WeaponProfileAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("WeaponProfileId", "AbilityId")
                        .IsUnique();

                    b.ToTable("WeaponProfileAbilities", (string)null);
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.ModelAbility", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Model", "Model")
                        .WithMany("ModelAbilities")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.ModelWargear", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Model", "Model")
                        .WithMany("ModelWargears")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Wargear", "Wargear")
                        .WithMany("ModelWargears")
                        .HasForeignKey("WargearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Wargear");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.ModelWeapon", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Model", "Model")
                        .WithMany("ModelWeapons")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Weapon", "Weapon")
                        .WithMany("ModelWeapons")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.OptionItem", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.UnitOption", "UnitOption")
                        .WithMany("OptionItems")
                        .HasForeignKey("UnitOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Wargear", "Wargear")
                        .WithMany()
                        .HasForeignKey("WargearId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StatHammer.Server.Models.Entities.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UnitOption");

                    b.Navigation("Wargear");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitAbility", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Unit", "Unit")
                        .WithMany("UnitAbilities")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitKeyword", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Keyword", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Unit", "Unit")
                        .WithMany("UnitKeywords")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitModel", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.Unit", "Unit")
                        .WithMany("UnitModels")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitOption", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Unit", "Unit")
                        .WithMany("UnitOptions")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.WeaponProfile", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Weapon", "Weapon")
                        .WithMany("WeaponProfiles")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.WeaponProfileAbility", b =>
                {
                    b.HasOne("StatHammer.Server.Models.Entities.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StatHammer.Server.Models.Entities.WeaponProfile", "WeaponProfile")
                        .WithMany("WeaponProfileAbilities")
                        .HasForeignKey("WeaponProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("WeaponProfile");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Model", b =>
                {
                    b.Navigation("ModelAbilities");

                    b.Navigation("ModelWargears");

                    b.Navigation("ModelWeapons");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Unit", b =>
                {
                    b.Navigation("UnitAbilities");

                    b.Navigation("UnitKeywords");

                    b.Navigation("UnitModels");

                    b.Navigation("UnitOptions");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.UnitOption", b =>
                {
                    b.Navigation("OptionItems");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Wargear", b =>
                {
                    b.Navigation("ModelWargears");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.Weapon", b =>
                {
                    b.Navigation("ModelWeapons");

                    b.Navigation("WeaponProfiles");
                });

            modelBuilder.Entity("StatHammer.Server.Models.Entities.WeaponProfile", b =>
                {
                    b.Navigation("WeaponProfileAbilities");
                });
#pragma warning restore 612, 618
        }
    }
}
